name: Greeting from Mona

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Download CodeTogether
        env:
          VERSION: 2023.1.1
          TIMESTAMP: 20230419
          TIME: 1410
          
        run: |
          wget https://downloads.genuitec.com/downloads/codetogether/extension/ct$TIMESTAMP/codetogether-$VERSION-0$TIME.zip
