name: CodeTogether-Production-Tests

on: push

jobs:
  my-job:
    name: Run CodeTogether-Production-Tests
    runs-on: macos-latest
    steps:
      - name: Install gradle
          
        run: |
          brew install gradle
          gradle --v
      - name: Download CodeTogether
        env:
          VERSION: 2023.1.1
          TIMESTAMP: 20230419
          TIME: 1410
          
        run: |
          wget https://downloads.genuitec.com/downloads/codetogether/extension/ct$TIMESTAMP/codetogether-$VERSION-0$TIME.zip
      
      - name: Run npm install
          
        run: |
          npm install
     
