name: CodeTogether-Production-Tests

on: push

jobs:
  my-job:
    name: Run CodeTogether-Production-Tests
    runs-on: windows-latest
    steps:
      - name: Download CodeTogether
        env:
          VERSION: 2023.1.1
          TIMESTAMP: 20230419
          TIME: 1410
          
        run: |
          curl.exe https://downloads.genuitec.com/downloads/codetogether/extension/ct"$TIMESTAMP"/codetogether-"$VERSION"-0"$TIME".zip
      
      - name: Run npm install
          
        run: |
          npm install
     
